apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: gateway
    group: "z00427ka"
    version: "1.8-SNAPSHOT"
  name: gateway
data:
  application-route.yml: |-
    gateway:
      routes:
        - name: "fashion"
          serviceId: "fashion-bestseller"
          route: "/fashion/**"
        - name: "hotdeals"
          serviceId: "hot-deals"
          route: "/hotdeals/**"
