---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    labels:
      app: "gateway"
      version: "1.0-SNAPSHOT"
      group: "z00427ka"
    name: "gateway"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "gateway"
      version: "1.0-SNAPSHOT"
      group: "z00427ka"
    name: "gateway"
  spec:
    ports:
    - name: "http"
      port: 8070
      targetPort: 8070
    selector:
      app: "gateway"
      version: "1.0-SNAPSHOT"
      group: "z00427ka"
    type: "NodePort"
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: namespace-reader
  rules:
    - apiGroups: [ "", "extensions", "apps" ]
      resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
      verbs: [ "get", "list", "watch" ]
- apiVersion: "rbac.authorization.k8s.io/v1"
  kind: "RoleBinding"
  metadata:
    labels:
      app: "gateway"
      version: "1.0-SNAPSHOT"
      group: "z00427ka"
    name: "gateway:view"
  roleRef:
    kind: "Role"
    name: "namespace-reader"
    apiGroup: ""
  subjects:
  - kind: "ServiceAccount"
    name: "gateway"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "gateway"
      version: "1.0-SNAPSHOT"
      group: "z00427ka"
    name: "gateway"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "gateway"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
    template:
      metadata:
        labels:
          app: "gateway"
          version: "1.0-SNAPSHOT"
          group: "z00427ka"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "vishakvinod/docker/gateway:1.16-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8070
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          name: "gateway"
          ports:
          - containerPort: 8070
            name: "http"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8070
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
        serviceAccount: "gateway"
        imagePullSecrets:
          - name: regcred
