---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "ServiceAccount"
    metadata:
      labels:
        app: "hot-deals"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
      name: "hot-deals"
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      labels:
        app: "hot-deals"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
      name: "hot-deals"
    spec:
      ports:
        - name: "http"
          port: 8083
          targetPort: 8083
      selector:
        app: "hot-deals"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
      type: "NodePort"
  - apiVersion: "rbac.authorization.k8s.io/v1"
    kind: "RoleBinding"
    metadata:
      labels:
        app: "hot-deals"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
      name: "hot-deals:view"
    roleRef:
      kind: "ClusterRole"
      apiGroup: "rbac.authorization.k8s.io"
      name: "view"
    subjects:
      - kind: "ServiceAccount"
        name: "hot-deals"
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "hot-deals"
        version: "1.0-SNAPSHOT"
        group: "z00427ka"
      name: "hot-deals"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: "hot-deals"
          version: "1.0-SNAPSHOT"
          group: "z00427ka"
      template:
        metadata:
          labels:
            app: "hot-deals"
            version: "1.0-SNAPSHOT"
            group: "z00427ka"
        spec:
          containers:
            - env:
                - name: "GATEWAY_URL"
                  value: http://gateway.wb-test.svc.cluster.local:8070
                - name: "KUBERNETES_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
              image: "vishakvinod/docker/hot-deals:1.4-SNAPSHOT"
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                httpGet:
                  path: "/actuator/health"
                  port: 8083
                  scheme: "HTTP"
                initialDelaySeconds: 0
                periodSeconds: 30
                timeoutSeconds: 10
              name: "hot-deals"
              ports:
                - containerPort: 8083
                  name: "http"
                  protocol: "TCP"
              readinessProbe:
                httpGet:
                  path: "/actuator/health"
                  port: 8083
                  scheme: "HTTP"
                initialDelaySeconds: 0
                periodSeconds: 30
                timeoutSeconds: 10
          serviceAccount: "hot-deals"
          imagePullSecrets:
            - name: regcred
